In [1]:
print("Hello")

Hello

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("Datasets\Dataset_python.csv")

In [4]:
dataset.head()

,Unnamed: 0,Country name,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality,Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year"
0,1,Afghanistan,2008,3.723590,7.168690,0.450662,50.799999,0.718114,0.177889,0.881686,0.517637,0.258195,0.612072,-1.929690,-1.655084,1.774662,0.476600,NaN,NaN
1,2,Afghanistan,2009,4.401778,7.333790,0.552308,51.200001,0.678896,0.200178,0.850035,0.583926,0.237092,0.611545,-2.044093,-1.635025,1.722688,0.391362,NaN,0.441906
2,3,Afghanistan,2010,4.758381,7.386629,0.539075,51.599998,0.600127,0.134353,0.706766,0.618265,0.275324,0.299357,-1.991810,-1.617176,1.878622,0.394803,NaN,0.327318
3,4,Afghanistan,2011,3.831719,7.415019,0.521104,51.919998,0.495901,0.172137,0.731109,0.611387,0.267175,0.307386,-1.919018,-1.616221,1.785360,0.465942,NaN,0.336764
4,5,Afghanistan,2012,3.782938,7.517126,0.520637,52.240002,0.530935,0.244273,0.775620,0.710385,0.267919,0.435440,-1.842996,-1.404078,1.798283,0.475367,NaN,0.344540

In [9]:
dataset_1 = dataset.loc[dataset['Year'].isin([2017,2018])]

In [13]:
(dataset_1["Year"]== 2018).sum()

136

In [14]:
(dataset_1["Year"]== 2017).sum()

147

In [18]:
((dataset_1["Year"]== 2017)!=(dataset_1["Year"]== 2018))

283

In [24]:
df_1 = dataset_1.groupby("Country name")
df_2 = df_1.filter(lambda x: len(x)>1)

In [25]:
(df_2["Year"]== 2018).sum()

131

In [26]:
(df_2["Year"]== 2017).sum()

131

In [27]:
df_2.describe()

,Unnamed: 0,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality,Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year"
count,262.000000,262.000000,262.000000,251.000000,261.000000,258.000000,261.000000,249.000000,247.000000,260.000000,260.000000,239.000000,131.000000,131.000000,262.000000,262.000000,238.000000,258.000000
mean,858.019084,2017.500000,5.506385,9.291332,0.811945,64.627632,0.783929,-0.020012,0.727810,0.707335,0.291557,0.497776,-0.095488,0.027074,2.236628,0.432533,0.383768,0.459490
std,491.191494,0.500957,1.115067,1.162028,0.114333,6.750827,0.122353,0.159782,0.188486,0.109145,0.086159,0.204449,0.856284,0.969788,0.493667,0.155195,0.082756,0.116422
min,10.000000,2017.000000,2.661718,6.623784,0.435879,47.700001,0.373536,-0.336385,0.096563,0.420962,0.092696,0.079710,-2.326562,-1.840400,1.198477,0.165445,0.211000,0.245601
25%,443.000000,2017.000000,4.659800,8.483234,0.739956,59.200001,0.716694,-0.149109,0.679009,0.623361,0.220249,0.325040,-0.682128,-0.675736,1.863424,0.311571,0.322471,0.375311
50%,872.500000,2017.500000,5.480884,9.481223,0.830768,66.250000,0.807142,-0.036960,0.789710,0.725317,0.286480,0.473674,-0.190968,-0.175471,2.206299,0.408930,0.368750,0.435504
75%,1277.500000,2018.000000,6.317309,10.210910,0.906699,69.225002,0.883905,0.078604,0.851420,0.793708,0.356030,0.628473,0.662567,0.803627,2.590833,0.541179,0.429903,0.552165
max,1704.000000,2018.000000,7.858107,11.454002,0.984489,76.800003,0.985178,0.629577,0.954393,0.883581,0.543836,0.988120,1.575009,2.069170,3.718958,0.938136,0.626000,0.852040

In [30]:
df_2.isnan

AttributeError: 'DataFrame' object has no attribute 'isnan'

In [34]:
df_2.isnull().sum()

Unnamed: 0                                                    0
Country name                                                  0
Year                                                          0
Life Ladder                                                   0
Log GDP per capita                                           11
Social support                                                1
Healthy life expectancy at birth                              4
Freedom to make life choices                                  1
Generosity                                                   13
Perceptions of corruption                                    15
Positive affect                                               2
Negative affect                                               2
Confidence in national government                            23
Democratic Quality                                          131
Delivery Quality                                            131
Standard deviation of ladder by country-year                  0
Standard deviation/Mean of ladder by country-year             0
GINI index (World Bank estimate), average 2000-16            24
gini of household income reported in Gallup, by wp5-year      4
dtype: int64

In [37]:
df_2.drop("Democratic Quality", axis =1 ,inplace=True)
df_2.drop("Delivery Quality",axis=1,inplace= True)

ValueError: labels ['Democratic Quality'] not contained in axis

In [38]:
df_2.head()

,Unnamed: 0,Country name,Year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,"GINI index (World Bank estimate), average 2000-16","gini of household income reported in Gallup, by wp5-year"
9,10,Afghanistan,2017,2.661718,7.497755,0.490880,52.799999,0.427011,-0.112198,0.954393,0.496349,0.371326,0.261179,1.454051,0.546283,NaN,0.286599
10,11,Afghanistan,2018,2.694303,7.494588,0.507516,52.599998,0.373536,-0.084888,0.927606,0.424125,0.404904,0.364666,1.408344,0.522712,NaN,0.290681
20,21,Albania,2017,4.639548,9.376145,0.637698,68.400002,0.749611,-0.032643,0.876135,0.669241,0.333884,0.457738,2.682105,0.578096,0.30325,0.410488
21,22,Albania,2018,5.004403,9.412399,0.683592,68.699997,0.824212,0.005385,0.899129,0.713300,0.318997,0.435338,2.640531,0.527642,0.30325,0.456174
27,28,Algeria,2017,5.248912,9.540639,0.806754,65.699997,0.436670,-0.191522,0.699774,0.641980,0.288710,NaN,2.039765,0.388607,0.27600,0.527556

In [42]:
import sklearn
from sklearn.preprocessing import Imputer
import numpy as np

In [44]:
imp= Imputer(missing_values=np.nan, strategy ="mean")
imp.fit(df_2[,2:])

ValueError: could not convert string to float: 'Zimbabwe'

In [47]:
df_3=df_2.fillna(df_2.mean())

In [48]:
df_3.isnull().sum()

Unnamed: 0                                                  0
Country name                                                0
Year                                                        0
Life Ladder                                                 0
Log GDP per capita                                          0
Social support                                              0
Healthy life expectancy at birth                            0
Freedom to make life choices                                0
Generosity                                                  0
Perceptions of corruption                                   0
Positive affect                                             0
Negative affect                                             0
Confidence in national government                           0
Standard deviation of ladder by country-year                0
Standard deviation/Mean of ladder by country-year           0
GINI index (World Bank estimate), average 2000-16           0
gini of household income reported in Gallup, by wp5-year    0
dtype: int64

In [49]:
df_3.to_csv("Dataset_Cleaned_Python.csv")